### PR TITLE
feat(get-prop): add dot path getter

### PR DESCRIPTION
**Pull request by pevisscher**

### CODE REVIEW

**Comment by pevisscher** [comment]
Current dependencies on/for this PR:
* main
  * **PR #86** <a href="https://app.graphite.dev/github/pr/skyleague/axioms/86" target="_blank">Graphite</a> 
    * **PR #87** <a href="https://app.graphite.dev/github/pr/skyleague/axioms/87" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/axioms/87?utm_source=stack-comment).

**Comment by pevisscher** [comment]
Current dependencies on/for this PR:
* main
  * **PR #86** <a href="https://app.graphite.dev/github/pr/skyleague/axioms/86" target="_blank">Graphite</a> 
    * **PR #87** <a href="https://app.graphite.dev/github/pr/skyleague/axioms/87" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/axioms/87?utm_source=stack-comment).

**Review by MickVanDuijn — APPROVED** [review]

**Comment by pevisscher** [comment]
@pevisscher started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/skyleague/axioms/87).

**Comment by pevisscher** [comment]
[Graphite](https://app.graphite.dev/github/pr/skyleague/axioms/87) rebased this pull request as part of a merge.

**Comment by pevisscher** [comment]
@pevisscher merged this pull request with [Graphite](https://app.graphite.dev/github/pr/skyleague/axioms/87).

**Pull request merged**
